import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://cas.baidu.com/?tpl=www2&fromu=https%3A%2F%2Fwww2.baidu.com%2Fcommon%2Fappinit.ajax")
    page.get_by_role("textbox", name="请输入账号").click()
    page.get_by_role("textbox", name="请输入账号").fill("BDCC-金蛛账号中心")
    page.get_by_role("textbox", name="请输入密码").click()
    page.get_by_role("textbox", name="请输入密码").fill("JinZhu2025#")
    page.get_by_role("button", name="登录").click()
    with page.expect_popup() as page1_info:
        page.get_by_text("金蛛-新账户5").click()
    page1 = page1_info.value
    with page1.expect_popup() as page2_info:
        page1.get_by_role("strong").filter(has_text="营销通").click()
    page2 = page2_info.value
    page2.get_by_role("dialog").get_by_role("button", name="​", exact=True).click()
    page2.get_by_text("通用咨询").click()
    page2.get_by_role("button", name="​ 新建咨询方案").click()
    page2.get_by_role("button", name="​ 创建").click()
    page2.get_by_role("textbox", name="咨询方案名称").click()
    page2.get_by_role("textbox", name="咨询方案名称").fill("一跳")
    page2.get_by_text("请选择客服账号").nth(1).click()
    page2.get_by_text("全时易聊").click()
    page2.get_by_text("请选择一级").nth(1).click()
    page2.get_by_role("option", name="百度基木鱼接待组").click()
    page2.get_by_role("button", name="​ 下一步").click()
    page2.locator("span").filter(has_text="请选择或输入名称新建商家卡片").locator("path").click()
    page2.locator("div").filter(has_text=re.compile(r"^请选择或输入名称$")).nth(2).click()
    page2.get_by_text("高级图文卡片").click()
    page2.get_by_text("北大青鸟深圳总校").click()
    page2.get_by_role("banner").filter(has_text="品牌优势卡展示商家服务特色，突出优势标签信息").get_by_role("switch").click()
    page2.get_by_text("请选择或输入名称").nth(1).click()
    page2.get_by_text("北大青鸟", exact=True).click()
    page2.locator("div").filter(has_text=re.compile(r"^人员卡片选择基木鱼-内容中心设置的人员分组，对推荐的人员信息进行动态展示样式示意选择人员物料全部选择分组不选择新建更多物料$")).get_by_label("不选择").check()
    page2.get_by_role("button", name="​ 下一步").click()
    page2.get_by_role("banner").filter(has_text="欢迎语访客进入后自动显示的问候语，为保障体验，如未设置则展示默认欢迎语").get_by_role("switch").click()
    page2.locator("#text-elem05930747577667295").fill("您好，是想咨询什么专业呢？如果比较迷茫也可以直接让老师给你推荐专业。")
    page2.get_by_role("banner").filter(has_text="快捷咨询底部常驻按钮，访客点击按钮即可获得相关信息").get_by_role("switch").click()
    page2.get_by_text("表单回复").click()
    page2.get_by_role("radio", name="选择已有表单 ​").check()
    page2.get_by_text("请选择或输入名称").nth(1).click()
    page2.get_by_role("option", name="咨询-预约看校").click()
    page2.get_by_role("textbox", name="请输入按钮文案，最多10个字符").click()
    page2.get_by_role("textbox", name="请输入按钮文案，最多10个字符").fill("预约看校")
    page2.get_by_text("添加快捷咨询").click()
    page2.get_by_text("添加快捷咨询").click()
    page2.get_by_text("添加快捷咨询").click()
    page2.get_by_text("*按钮文案8/10*回复内容图文回复文字回复页面跳转表单回复卡券发放热门商品*表单方案新建表单选择已有表单请选择或输入名称咨询-预约看校 添加快捷咨询").click()
    page2.get_by_text("添加快捷咨询").click()
    page2.get_by_role("banner").filter(has_text="电话设置客户可在咨询页设置电话方案、按钮文字等内容").get_by_role("switch").click()
    page2.get_by_text("请选择或输入名称").nth(2).click()
    page2.get_by_text("智能-18466200090转").click()
    page2.get_by_text("此设置可能会影响用户咨询开口率，请谨慎勾选，勾选后，在输入框上方区域补充展示电话按钮 ，仅对咨询型落地页生效查看示意图").click()
    page2.locator("input[name=\"checkbox\"]").check()
    page2.get_by_role("textbox", name="请输入按钮文字，最多10个字符").click()
    page2.get_by_role("textbox", name="请输入按钮文字，最多10个字符").fill("电话沟通")
    page2.get_by_text("添加快捷咨询").click()
    page2.locator("span").filter(has_text=re.compile(r"^请选择或输入名称$")).click()
    page2.locator("div:nth-child(2) > div:nth-child(3) > .consult-detail-container-quickconsulting-content > .consult-detail-common-replay > .one-radio-group > .one-radio-group-items > label:nth-child(4) > .one-radio > .one-radio-inner").click()
    page2.locator(".one-cascader-picker-main").click()
    page2.locator("span").filter(has_text=re.compile(r"^请选择或输入名称$")).click()
    page2.locator(".one-cascader-picker-main").click()
    page2.locator("div").filter(has_text=re.compile(r"^\*回复内容图文回复文字回复页面跳转表单回复卡券发放热门商品请选择或输入名称$")).get_by_label("表单回复").check()
    page2.locator("div:nth-child(2) > div:nth-child(3) > .consult-detail-container-quickconsulting-content > .consult-detail-common-replay > .consult-detail-common-replay-child > .form-reply-wrapper > div > .form-field-control > .one-radio-group > .one-radio-group-items > label:nth-child(2) > .one-radio > .one-radio-inner").click()
    page2.locator("div").filter(has_text=re.compile(r"^\*回复内容图文回复文字回复页面跳转表单回复卡券发放热门商品\*表单方案新建表单选择已有表单\*表单模版请选择预约式表单标题8/50按钮文案8\/30$")).get_by_label("选择已有表单").check()
    page2.get_by_text("请选择或输入名称").nth(2).click()
    page2.get_by_role("option", name="咨询-学费补贴").click()
    page2.locator("div").filter(has_text=re.compile(r"^\*按钮文案0/10$")).get_by_placeholder("请输入按钮文案，最多10个字符").click()
    page2.locator("div").filter(has_text=re.compile(r"^\*按钮文案0/10$")).get_by_placeholder("请输入按钮文案，最多10个字符").fill("学费补贴")
    page2.get_by_role("button", name="​ 创建").click()
    page2.goto("https://yingxiaotong.baidu.com/vector/user/64951865/component/consult/newList")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
